config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: "home#index"

  resources :claim_reviews
  resources :review_ratings
  resources :item_revieweds
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item_reviewed.rb
class ItemReviewed < ApplicationRecord
    belongs_to :author
    has_many :claim_review
end

app/controllers/item_revieweds_controller.rb
class ItemReviewedsController < ApplicationController
  before_action :set_item_reviewed, only: [:show, :edit, :update, :destroy]

  # GET /item_revieweds
  # GET /item_revieweds.json
  def index
    @item_revieweds = ItemReviewed.all
  end

  # GET /item_revieweds/1
  # GET /item_revieweds/1.json
  def show
  end

  # GET /item_revieweds/new
  def new
    @item_reviewed = ItemReviewed.new
  end

  # GET /item_revieweds/1/edit
  def edit
  end

  # POST /item_revieweds
  # POST /item_revieweds.json
  def create
    @item_reviewed = ItemReviewed.new(item_reviewed_params)

    respond_to do |format|
      if @item_reviewed.save
        format.html { redirect_to @item_reviewed, notice: 'Item reviewed was successfully created.' }
        format.json { render :show, status: :created, location: @item_reviewed }
      else
        format.html { render :new }
        format.json { render json: @item_reviewed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_revieweds/1
  # PATCH/PUT /item_revieweds/1.json
  def update
    respond_to do |format|
      if @item_reviewed.update(item_reviewed_params)
        format.html { redirect_to @item_reviewed, notice: 'Item reviewed was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_reviewed }
      else
        format.html { render :edit }
        format.json { render json: @item_reviewed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_revieweds/1
  # DELETE /item_revieweds/1.json
  def destroy
    @item_reviewed.destroy
    respond_to do |format|
      format.html { redirect_to item_revieweds_url, notice: 'Item reviewed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_reviewed
      @item_reviewed = ItemReviewed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_reviewed_params
      params.require(:item_reviewed).permit(:ir_type, :author_id, :url, :datepublished)
    end
end

app/helpers/item_revieweds_helper.rb
module ItemReviewedsHelper
end

app/views/item_revieweds/_form.html.erb
<%= form_with(model: item_reviewed, local: true) do |form| %>
  <% if item_reviewed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_reviewed.errors.count, "error") %> prohibited this item_reviewed from being saved:</h2>

      <ul>
      <% item_reviewed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.collection_select :ir_type, ['CreativeWork'], :to_s, :to_s %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.collection_select :author_id, Author.order(:name),:id,:name, include_blank: false %>
    <%= link_to 'New Author', '/authors/new' %>
  </div>

  <div class="field">
    <%= form.label :datepublished %>
    <%= form.date_select :datepublished, id: :item_reviewed_datepublished %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/item_revieweds/edit.html.erb
<h1>Editing Item Reviewed</h1>

<%= render 'form', item_reviewed: @item_reviewed %>

<%= link_to 'Show', @item_reviewed %> |
<%= link_to 'Back', item_revieweds_path %>

app/views/item_revieweds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Revieweds</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Author</th>
      <th>URL</th>
      <th>Datepublished</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_revieweds.each do |item_reviewed| %>
      <tr>
        <td><%= item_reviewed.ir_type %></td>
        <td><%= item_reviewed.author_id %></td>
        <td><%= item_reviewed.url %></td>
        <td><%= item_reviewed.datepublished %></td>
        <td><%= link_to 'Show', item_reviewed %></td>
        <td><%= link_to 'Edit', edit_item_reviewed_path(item_reviewed) %></td>
        <td><%= link_to 'Destroy', item_reviewed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Reviewed', new_item_reviewed_path %>

app/views/item_revieweds/new.html.erb
<h1>New Item Reviewed</h1>

<%= render 'form', item_reviewed: @item_reviewed %>

<%= link_to 'Back', item_revieweds_path %>

app/views/item_revieweds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @item_reviewed.ir_type %>
</p>

<p>
  <strong>Author:</strong>
  <%= @item_reviewed.author.name %>
</p>

<p>
  <strong>URL</strong>
  <%= @item_reviewed.url %>
</p>

<p>
  <strong>Datepublished:</strong>
  <%= @item_reviewed.datepublished %>
</p>

<%= link_to 'Edit', edit_item_reviewed_path(@item_reviewed) %> |
<%= link_to 'Back', item_revieweds_path %> |
<%= link_to 'Create ClaimReview', '/claim_reviews/new' %>