config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: "home#index"

  resources :claim_reviews
  resources :review_ratings
  resources :item_revieweds
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/review_rating.rb
class ReviewRating < ApplicationRecord
    has_many :claim_review
end

app/controllers/review_ratings_controller.rb
class ReviewRatingsController < ApplicationController
  before_action :set_review_rating, only: [:show, :edit, :update, :destroy]

  # GET /review_ratings
  # GET /review_ratings.json
  def index
    @review_ratings = ReviewRating.all
  end

  # GET /review_ratings/1
  # GET /review_ratings/1.json
  def show
  end

  # GET /review_ratings/new
  def new
    @review_rating = ReviewRating.new
  end

  # GET /review_ratings/1/edit
  def edit
  end

  # POST /review_ratings
  # POST /review_ratings.json
  def create
    @review_rating = ReviewRating.new(review_rating_params)

    respond_to do |format|
      if @review_rating.save
        format.html { redirect_to @review_rating, notice: 'Review rating was successfully created.' }
        format.json { render :show, status: :created, location: @review_rating }
      else
        format.html { render :new }
        format.json { render json: @review_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /review_ratings/1
  # PATCH/PUT /review_ratings/1.json
  def update
    respond_to do |format|
      if @review_rating.update(review_rating_params)
        format.html { redirect_to @review_rating, notice: 'Review rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @review_rating }
      else
        format.html { render :edit }
        format.json { render json: @review_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /review_ratings/1
  # DELETE /review_ratings/1.json
  def destroy
    @review_rating.destroy
    respond_to do |format|
      format.html { redirect_to review_ratings_url, notice: 'Review rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review_rating
      @review_rating = ReviewRating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_rating_params
      params.require(:review_rating).permit(:rr_type, :ratingValue, :bestRating, :worstRating, :alternateName)
    end
end

app/helpers/review_ratings_helper.rb
module ReviewRatingsHelper
end

app/views/review_ratings/_form.html.erb
<%= form_with(model: review_rating, local: true) do |form| %>
  <% if review_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review_rating.errors.count, "error") %> prohibited this review_rating from being saved:</h2>

      <ul>
      <% review_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :rr_type, id: :review_rating_type %>
  </div>

  <div class="field">
    <%= form.label :ratingValue %>
    <%= form.text_field :ratingValue, id: :review_rating_ratingValue %>
  </div>

  <div class="field">
    <%= form.label :bestRating %>
    <%= form.text_field :bestRating, id: :review_rating_bestRating %>
  </div>

  <div class="field">
    <%= form.label :worstRating %>
    <%= form.text_field :worstRating, id: :review_rating_worstRating %>
  </div>

  <div class="field">
    <%= form.label :alternateName %>
    <%= form.text_field :alternateName, id: :review_rating_alternateName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/review_ratings/edit.html.erb
<h1>Editing Review Rating</h1>

<%= render 'form', review_rating: @review_rating %>

<%= link_to 'Show', @review_rating %> |
<%= link_to 'Back', review_ratings_path %>

app/views/review_ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Review Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Ratingvalue</th>
      <th>Bestrating</th>
      <th>Worstrating</th>
      <th>Alternatename</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @review_ratings.each do |review_rating| %>
      <tr>
        <td><%= review_rating.rr_type %></td>
        <td><%= review_rating.ratingValue %></td>
        <td><%= review_rating.bestRating %></td>
        <td><%= review_rating.worstRating %></td>
        <td><%= review_rating.alternateName %></td>
        <td><%= link_to 'Show', review_rating %></td>
        <td><%= link_to 'Edit', edit_review_rating_path(review_rating) %></td>
        <td><%= link_to 'Destroy', review_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review Rating', new_review_rating_path %> | 
<%= link_to 'New Claim Review', new_claim_review_path %>

app/views/review_ratings/new.html.erb
<h1>New Review Rating</h1>

<%= render 'form', review_rating: @review_rating %>

<%= link_to 'Back', review_ratings_path %>

app/views/review_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @review_rating.rr_type %>
</p>

<p>
  <strong>Ratingvalue:</strong>
  <%= @review_rating.ratingValue %>
</p>

<p>
  <strong>Bestrating:</strong>
  <%= @review_rating.bestRating %>
</p>

<p>
  <strong>Worstrating:</strong>
  <%= @review_rating.worstRating %>
</p>

<p>
  <strong>Alternatename:</strong>
  <%= @review_rating.alternateName %>
</p>

<%= link_to 'Edit', edit_review_rating_path(@review_rating) %> |
<%= link_to 'Back', review_ratings_path %>