config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: "home#index"

  resources :claim_reviews
  resources :review_ratings
  resources :item_revieweds
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/claim_reviews_controller.rb
class ClaimReviewsController < ApplicationController
  before_action :set_claim_review, only: [:show, :edit, :update, :destroy]

  # GET /claim_reviews
  # GET /claim_reviews.json
  def index
    @claim_reviews = ClaimReview.all
  end

  # GET /claim_reviews/1
  # GET /claim_reviews/1.json
  def show
    # @claim_review = {
    #   "@context": "http://schema.org",
    #   "@type": "ClaimReview",
    #   "datePublished": @claim_review.datePublished,
    #   "url": @claim_review.url,
    #   "itemReviewed":
    #   {
    #     "@type": @claim_review.item_reviewed.ir_type,
    #     "author":
    #     {
    #       "@type": @claim_review.item_reviewed.author.author_type,
    #       "name": @claim_review.item_reviewed.author.name,
    #       "sameAs": @claim_review.item_reviewed.url
    #     },
    #     "datePublished": @claim_review.item_reviewed.datepublished
    #   },
    #   "claimReviewed": @claim_review.claimReviewed,
    #   "author":
    #   {
    #     "@type": @claim_review.author.author_type,
    #     "name": @claim_review.author.name
    #   },
    #   "reviewRating":
    #   {
    #     "@type": @claim_review.review_rating.rr_type,
    #     "ratingValue": @claim_review.review_rating.ratingValue,
    #     "bestRating": @claim_review.review_rating.bestRating,
    #     "worstRating": @claim_review.review_rating.worstRating,
    #     "alternateName": @claim_review.review_rating.alternateName
    #   }
    # }
  end

  # GET /claim_reviews/new
  def new
    @claim_review = ClaimReview.new
  end

  # GET /claim_reviews/1/edit
  def edit
  end

  # POST /claim_reviews
  # POST /claim_reviews.json
  def create
    @claim_review = ClaimReview.new(claim_review_params)

    respond_to do |format|
      if @claim_review.save
        format.html { redirect_to @claim_review, notice: 'Claim review was successfully created.' }
        format.json { render :show, status: :created, location: @claim_review }
      else
        format.html { render :new }
        format.json { render json: @claim_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claim_reviews/1
  # PATCH/PUT /claim_reviews/1.json
  def update
    respond_to do |format|
      if @claim_review.update(claim_review_params)
        format.html { redirect_to @claim_review, notice: 'Claim review was successfully updated.' }
        format.json { render :show, status: :ok, location: @claim_review }
      else
        format.html { render :edit }
        format.json { render json: @claim_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claim_reviews/1
  # DELETE /claim_reviews/1.json
  def destroy
    @claim_review.destroy
    respond_to do |format|
      format.html { redirect_to claim_reviews_url, notice: 'Claim review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim_review
      @claim_review = ClaimReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_review_params
      params.require(:claim_review).permit(:datePublished, :url, :item_reviewed_id, :claimReviewed, :author_id, :review_rating_id)
    end
end

app/helpers/claim_reviews_helper.rb
module ClaimReviewsHelper
end

app/views/claim_reviews/_form.html.erb
<%= form_with(model: claim_review, local: true) do |form| %>
  <% if claim_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(claim_review.errors.count, "error") %> prohibited this claim_review from being saved:</h2>

      <ul>
      <% claim_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :datePublished %>
    <%= form.date_select :datePublished, id: :claim_review_datePublished %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :claim_review_url %>
  </div>

  <div class="field">
    <%= form.label :item_reviewed_id %>
    <%= form.collection_select :item_reviewed_id, ItemReviewed.order(:url),:id,:url, include_blank: false %>
    <%= link_to 'New Item', '/item_revieweds/new' %>
  </div>

  <div class="field">
    <%= form.label 'Claim Made in the Item' %>
    <%= form.text_field :claimReviewed, id: :claim_review_claimReviewed %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.collection_select :author_id, Author.order(:name),:id,:name, include_blank: false %>
    <%= link_to 'New Author', '/authors/new' %>
  </div>

  <div class="field">
    <%= form.label :review_rating_id %>
    <%= form.collection_select :review_rating_id, ReviewRating.order(:ratingValue),:id,:alternateName, include_blank: false %>
    <%= link_to 'New Rating', '/review_ratings/new' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/claim_reviews/edit.html.erb
<h1>Editing Claim Review</h1>

<%= render 'form', claim_review: @claim_review %>

<%= link_to 'Show', @claim_review %> |
<%= link_to 'Back', claim_reviews_path %>

app/views/claim_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Claim Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Datepublished</th>
      <th>Url</th>
      <th>Item reviewed</th>
      <th>Claimreviewed</th>
      <th>Claim Author</th>
      <th>Review rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @claim_reviews.each do |claim_review| %>
      <tr>
        <td><%= claim_review.datePublished %></td>
        <td><%= claim_review.url %></td>
        <td><%= claim_review.item_reviewed_id %></td>
        <td><%= claim_review.claimReviewed %></td>
        <td><%= claim_review.author.name %></td>
        <td><%= claim_review.review_rating_id %></td>
        <td><%= link_to 'Show', claim_review %></td>
        <td><%= link_to 'Edit', edit_claim_review_path(claim_review) %></td>
        <td><%= link_to 'Destroy', claim_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Claim Review', new_claim_review_path %>

app/views/claim_reviews/new.html.erb
<h1>New Claim Review</h1>

<%= render 'form', claim_review: @claim_review %>

<%= link_to 'Back', claim_reviews_path %>

app/views/claim_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datepublished:</strong>
  <%= @claim_review.datePublished %>
</p>

<p>
  <strong>Url:</strong>
  <%= @claim_review.url %>
</p>

<p>
  <strong>Item reviewed:</strong>
  <%= @claim_review.item_reviewed.url %>
</p>

<p>
  <strong>Claim Reviewed:</strong>
  <%= @claim_review.claimReviewed %>
</p>

<p>
  <strong>Author:</strong>
  <%= @claim_review.author.name %>
</p>

<p>
  <strong>Review rating:</strong>
  <%= @claim_review.review_rating_id %>
</p>

<%= link_to 'Edit', edit_claim_review_path(@claim_review) %> |
<%= link_to 'Back', claim_reviews_path %>

app/views/claim_reviews/show.json.erb
{
  "@context": "http://schema.org",
  "@type": "ClaimReview",
  "datePublished": "<%= @claim_review.datePublished %>",
  "url": "<%= @claim_review.url %>",
  "itemReviewed":
  {
    "@type": "<%= @claim_review.item_reviewed.ir_type %>",
    "author":
    {
      "@type": "<%= @claim_review.item_reviewed.author.author_type %>",
      "name": "<%= @claim_review.item_reviewed.author.name %>",
      "sameAs": "<%= @claim_review.item_reviewed.url %>"
    },
    "datePublished": "<%= @claim_review.item_reviewed.datepublished %>"
  },
  "claimReviewed": "<%= @claim_review.claimReviewed %>",
  "author":
  {
    "@type": "<%= @claim_review.author.author_type %>",
    "name": "<%= @claim_review.author.name %>"
  },
  "reviewRating":
  {
    "@type": "<%= @claim_review.review_rating.rr_type %>",
    "ratingValue": "<%= @claim_review.review_rating.ratingValue %>",
    "bestRating": "<%= @claim_review.review_rating.bestRating %>",
    "worstRating": "<%= @claim_review.review_rating.worstRating %>",
    "alternateName": "<%= @claim_review.review_rating.alternateName %>"
  }
}